# yaml-language-server: $schema=https://cloud.dqo.ai/dqo-yaml-schema/TableYaml-schema.json
apiVersion: dqo/v1
kind: table
spec:
  target:
    schema_name: austin_crime
    table_name: crime
  time_series:
    mode: timestamp_column
    timestamp_column: timestamp
    time_gradient: day
  checks:
    timeliness:
      average_delay:
        parameters:
          column1: "clearance_date"
          column2: "timestamp"
        rules:
          moving_average:
            low:
              max_percent_above: 5.0
              max_percent_below: 5.0
            medium:
              max_percent_above: 10.0
              max_percent_below: 10.0
            high:
              max_percent_above: 15.0
              max_percent_below: 15.0
  columns:
    unique_key:
      type_snapshot:
        column_type: INT64
        nullable: true
    address:
      type_snapshot:
        column_type: STRING
        nullable: true
    census_tract:
      type_snapshot:
        column_type: FLOAT64
        nullable: true
    clearance_date:
      type_snapshot:
        column_type: TIMESTAMP
        nullable: true
    clearance_status:
      type_snapshot:
        column_type: STRING
        nullable: true
    council_district_code:
      type_snapshot:
        column_type: INT64
        nullable: true
    description:
      type_snapshot:
        column_type: STRING
        nullable: true
    district:
      type_snapshot:
        column_type: STRING
        nullable: true
    latitude:
      type_snapshot:
        column_type: FLOAT64
        nullable: true
    longitude:
      type_snapshot:
        column_type: FLOAT64
        nullable: true
    location:
      type_snapshot:
        column_type: STRING
        nullable: true
    location_description:
      type_snapshot:
        column_type: STRING
        nullable: true
    primary_type:
      type_snapshot:
        column_type: STRING
        nullable: true
    timestamp:
      type_snapshot:
        column_type: TIMESTAMP
        nullable: true
    x_coordinate:
      type_snapshot:
        column_type: INT64
        nullable: true
    y_coordinate:
      type_snapshot:
        column_type: INT64
        nullable: true
    year:
      type_snapshot:
        column_type: INT64
        nullable: true
    zipcode:
      type_snapshot:
        column_type: STRING
        nullable: true
