# yaml-language-server: $schema=https://cloud.dqo.ai/dqo-yaml-schema/TableYaml-schema.json
apiVersion: dqo/v1
kind: table
spec:
  target:
    schema_name: dqo_ai_test_data
    table_name: customers
  time_series:
    mode: current_time
    time_gradient: day
  columns:
    customer_age:
      type_snapshot:
        column_type: INT64
        nullable: true
      checks:
        validity:
          value_in_range_numerical_percent:
            parameters:
              min_value: 18.0
              max_value: 100.0
              include_max_value: false
            rules:
              min_count:
                low:
                  min_value: 90.0
                medium:
                  min_value: 80.0
                high:
                  min_value: 70.0