# yaml-language-server: $schema=https://cloud.dqo.ai/dqo-yaml-schema/TableYaml-schema.json
apiVersion: dqo/v1
kind: table
spec:
  target:
    schema_name: dqo_ai_test_data
    table_name: table
  time_series:
    mode: timestamp_column
    timestamp_column: date2
    time_gradient: day
  checks:
    timeliness:
      average_delay:
        parameters:
          column1: "date1"
          column2: "date2"
        rules:
          moving_average:
            low:
              max_percent_above: 5.0
              max_percent_below: 5.0
            medium:
              max_percent_above: 10.0
              max_percent_below: 10.0
            high:
              max_percent_above: 15.0
              max_percent_below: 15.0
  columns:
    id:
      type_snapshot:
        column_type: INT64
        nullable: true
    date1:
      type_snapshot:
        column_type: DATETIME
        nullable: true
    date2:
      type_snapshot:
        column_type: DATETIME
        nullable: true
