# yaml-language-server: $schema=https://cloud.dqo.ai/dqo-yaml-schema/TableYaml-schema.json
apiVersion: dqo/v1
kind: table
spec:
  target:
    schema_name: test_data
    table_name: email_addresses
  time_series:
    mode: current_time
    time_gradient: day
  columns:
    emails:
      type_snapshot:
        column_type: STRING
        nullable: true
      checks:
        validity:
          match_regex_percent:
            parameters:
              named_regex: email
            rules:
              count_equals:
                low:
                  expected_value: 95.0
                  error_margin: 2.0
                medium:
                  expected_value: 90.0
                  error_margin: 2.0
                high:
                  expected_value: 80.0
                  error_margin: 5.0