# yaml-language-server: $schema=https://cloud.dqo.ai/dqo-yaml-schema/TableYaml-schema.json
apiVersion: dqo/v1
kind: table
spec:
  target:
    schema_name: dqo_ai_test_data
    table_name: test_data_time_series_1901211650245440619
  time_series:
    mode: current_time
    time_gradient: day
  columns:
    id:
      type_snapshot:
        column_type: INT64
        nullable: true
    date_type:
      type_snapshot:
        column_type: DATE
        nullable: true
      checks:
        validity:
          value_in_range_date_percent:
            parameters:
              min_value:  "2019-12-23"
              max_value:  "2022-01-15"
              include_min_value: false
              include_max_value: false
            rules:
              min_count:
                low:
                  min_value: 90.0
                medium:
                  min_value: 90.0
                high:
                  min_value: 90.0
    mixed_mail:
      type_snapshot:
        column_type: STRING
        nullable: true
